on:
  workflow_dispatch:
  push:
    branches:
      - 'public_release/**'

jobs:
  static-analysis:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/static_analysis.yml@main
    with:
      project: OSS ChameleonRT
      server: prod5
      submodules: true
      prebuild: >
        sh .github/workflows/install_dependencies.sh &&
        export PATH="$(pwd)/build/cmake-current/bin:$PATH" &&
        export LANG=C.UTF-8 &&
        which cmake &&
        cmake --version &&
        cmake --preset vulkan
      build: cmake --build --preset vulkan
